INSERT INTO PRODUCT VALUES ('K9-BC-01','DOGS', 'Bichon','<image src="../images/dog7.gif">Beautiful puppy');
INSERT INTO  ITEM (ITEMID, PRODUCTID, LISTPRICE, UNITCOST, SUPPLIER, STATUS, ATTR1) VALUES('EST-29','K9-BC-01',199.99, 120.00,1,'P','Female Puppy');
INSERT INTO INVENTORY (ITEMID, QTY ) VALUES ('EST-29',10000);